### ISSUE TITLE
Card Type & Card Category SerializeName for Upper Case value 

### ISSUE THREAD

**Issue by shiuh-yaw-cko** [checkout/checkout-sdk-java#136]
Card Type & Card Category SerializeName for Upper Case value 

### Environment

* Checkout SDK version: 5.0.0
* Platform and version: JDK 8
* Operating System and version: Mac OS Monterey

### Description

Respone cardType=null, cardCategory=null within com.checkout.instruments.four.create.CreateInstrumentTokenResponse

### Expected behavior

Expecting to serialize value regardless upper case or lower case

### Current behavior

Response null for cardType, cardCategory

### Steps to reproduce

Request POST instruments API with a frames token (tok_), test card 4242 4242 4242 4242

### Possible solution

Update value serialization to handle both uppercase and lowercase

- [ ] I may be able to implement this bug fix

### Additional information

{
    "id": "src_zopuwjvpu4qerfas4rtbdq474u",
    "type": "card",
    "fingerprint": "918F0A098B1515A2860835C73550F40D0A2FAE9599F68AD969FEE893D81C51B1",
    "expiry_month": 12,
    "expiry_year": 2021,
    "scheme": "VISA",
    "last4": "4242",
    "bin": "424242",
    "card_type": "CREDIT",
    "card_category": "CONSUMER",
    "issuer": "JPMORGAN CHASE BANK NA",
    "issuer_country": "US",
    "product_id": "A",
    "product_type": "Visa Traditional",
    "customer": {
        "id": "cus_z6qkm7xgqu3epa6pgj4a543lgm",
        "name": "li mo",
        "email": "test@test.com"
    }
}

CreateInstrumentTokenResponse(super=CreateInstrumentResponse(id=src_gbpkdyguqtsenirm5ommyb2ttu), type=CARD, fingerprint=A730033CF77DE08C5BCED09FF3CE9919E4A9B5A117F2F0A2A61BCBA13E848DC8, expiryMonth=3, expiryYear=2033, scheme=VISA, last4=4242, bin=424242, cardType=null, cardCategory=null, issuer=JPMORGAN CHASE BANK NA, issuerCountry=US, productId=A, productType=Visa Traditional, customer=CustomerResponse(id=cus_vcuh4v44cu7ethfbhsagtayfla, email=chenyu.liu@gmail.com, name=James))

**Comment by Armando-Ibarra** [comment]
Hi @shiuh-yaw-cko 
I was able to repro the issue as well, and yes you are right, this is something unexpected and we will review with the team if the response has changed or why was the reason on the change.

In any case, we will provide the fix.

Regards.

**Comment by rsaestrela** [comment]
Hi @shiuh-yaw-cko. This is being fixed in #137. We will let you know and the issue will be closed when we release the fix. Thanks for opening this issue.

**Comment by rsaestrela** [comment]
This was been fixed in version 5.1.0.
