### ISSUE TITLE
The SDK doesn't support the dispute APIs

### ISSUE THREAD

**Issue by nkavian** [checkout/checkout-sdk-java#15]
I need to be able to retrieve a dispute via API.

As well, I need to pull the dispute object because the dispute webhook does not provide the dispute amount.

Both strangely missing on a great product and API.

**Comment by nicolas-maalouf-cko** [comment]
Hi @nkavian I will request the disputes API to be added to the sdk, but this usually takes a couple of weeks.

I assume you're listening to the `dispute_evidence_required` webhook? 

Thanks

**Comment by nkavian** [comment]
Hi @nicolas-maalouf-cko,

Yes, my use case is that I'm adding support for dispute webhooks, but I need to know the disputed amount. That information is not available in the webhook event, so I need to fetch the Dispute. When I investigated, the SDK does not have those APIs supported yet.

To be clear, I'm not interested in the POST dispute endpoints, that might be more complex for you to add. I just need the GET `/disputes/{disputeId}/` end point.

Where/How can I also request a non-SDK issue. Can you help me with that? -->

The Disputes documentation says that a webhook is not sent for `accepted ` status. A merchant needs to update their systems just as if they would when the `dispute_won` or `dispute_lost` webhooks are sent. My request is to support a `dispute_accepted` webhook.

https://docs.checkout.com/risk-management/disputes/disputes-api#DisputesAPI-Disputestatuses

Thanks,

Nas.

**Comment by rsaestrela** [comment]
Hi @nkavian. This feature was implemented recently and will be released in the upcoming weeks. Thank you for submitting this feature request.

**Comment by nkavian** [comment]
When you say "this feature", which one are you specifically referring you?

**Comment by nkavian** [comment]
@rsaestrela When you say "this feature", which one are you specifically referring you?

**Comment by rsaestrela** [comment]
Hi @nkavian, I was referring to the disputes support on this SDK. The [PR ](https://github.com/checkout/checkout-sdk-java/pull/53) was merged recently and this will support getting the dispute details by its id. 

More info here: https://github.com/checkout/checkout-sdk-java/blob/dev/documentation/docs/api/disputes.md
