### ISSUE TITLE
Missing instrument information (name, expiry_monty, expiry_year, last4, bin, card_type) for response type = 'card'

### ISSUE THREAD

**Issue by shiuh-yaw-cko** [checkout/checkout-sdk-java#162]
### Environment

* Checkout SDK version: lastest
* Platform and version: Four, Production
* Operating System and version: Linux

### Description

Missing instrument information (name, expiry_monty, expiry_year, last4, bin, card_type) for response type = 'card'
https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/instruments/four/get/GetInstrumentResponse.java

### Expected behavior

Expect instrument information returned from GET instrument API

### Current behavior

No card instrument information 

### Steps to reproduce

- Tokenize with Frames with name
- POST instruments
- GET instruments

### Possible solution

- Include additional instruments info based on API doc (https://api-reference.checkout.com/preview/crusoe/#operation/getInstrumentDetails)

- [ ] I may be able to implement this bug fix

**Comment by rsaestrela** [comment]
Hi @shiuh-yaw-cko. Thanks for creating this issue. 

`GetInstrumentResponse` is an abstract class. You should be able to get that information simply by casting the response to `GetCardInstrumentResponse`. The same applies to `GetBankAccountInstrumentResponse`.

```
GetCardInstrumentResponse response = (GetCardInstrumentResponse) api.instrumentsClient().get("instrument_id")
```
Please let me know if this solution worked for you.
