### ISSUE TITLE
How to get checkout api status

### ISSUE THREAD

**Issue by abbottyf** [checkout/checkout-sdk-java#2]
How to get the status of http of the api interface, the status is 200, 201, 400 and so on

**Comment by harry-peirse** [comment]
Hi, it's not possible as the SDK tries to convert the HTTP response into something more meaningful. If you are seeing errors it should always provide the requestId in the exception object so you can track it with Checkout.com. Is there a specific problem you're facing that having access to these would solve?

**Comment by harry-peirse** [comment]
Closing after two weeks without response. Feel free to reopen.
