### ISSUE TITLE
Please provide way to define own thread pool

### ISSUE THREAD

**Issue by keiki85** [checkout/checkout-sdk-java#23]
Hi,

a suggestion. Can you please provide a possibility to define our own thread pool. 

This has following advantages:

* Thread pool independent of fork join pool, which has a fixed size and shared with the JVM. If something goes wrong elsewhere payments are not possible anymore.
* clear naming of threads to distinguish them (especially in case where something goes wrong or is stuck)

Best regards

**Comment by nicolas-maalouf-cko** [comment]
Hi @keiki85 

Would you have the ability to provide a pull request with this enhancement?
Else this is being added to our backlog which will require a bit more time to be implemented.

Thank you

**Comment by harry-peirse** [comment]
Hi @keiki85, I know this doesn't fully solve the problem, but we are partially there with the 3.0.0 release which allows you to define an HTTP Connection Pool now that we are using apache http client internally - you have access to the HttpClientBuilder class via the CheckoutConfiguration class if you're interested. But we'll keep this issue open until we have a more complete threadpooling solution.

**Comment by rsaestrela** [comment]
Hi! #134 adds this feature, plus the ability to set a custom `HttpClientBuilder`. Will close this issue once the PR is merged.
