### ISSUE TITLE
SDK doesn't support KNET payments

### ISSUE THREAD

**Issue by anandb87** [checkout/checkout-sdk-java#244]
The latest version of the SDK doesn't have the provision to create KNET payment requests

### Environment
Checkout SDK version: 5.9.6

### Description
com.checkout.common.PaymentSourceType doesn't define source type for KNET. So it is not possible to create a source for KNET payments. The checkout API for KNET payments requires the source type to be "knet"

### Expected behavior
com.checkout.common.PaymentSourceType should have an enum defined for KNET

### Current behavior
PaymentSourceType doesn't define a source type for KNET payments

### Possible solution
Define source type "knet" in com.checkout.common.PaymentSourceType

- [x] I may be able to implement this bug fix

**Comment by Armando-Ibarra** [comment]
@anandb87 version 5.9.7 is released #246 
Please let us know if you're having any issues.

Thanks!
