### ISSUE TITLE
6.0.0 Where did the recon go?

### ISSUE THREAD

**Issue by rotilho** [checkout/checkout-sdk-java#252]
### Environment

* Checkout SDK version: 6.0.0
* Platform and version: SANDBOX
* Operating System and version: Windows

### Expected behavior

Recon method still exists in the new 6.0.0 or documentation how to migrate to the new version.

### Current behavior

Recon is gone and it seems I should use the classes from `.previous` package

### Steps to reproduce

Upgrade to 6.0.0

### Possible solution

- [ ] Deprecated method with docs explaining how to migrate
- [ ] Add migration page

**Comment by Armando-Ibarra** [comment]
Hi @rotilho 
Version 6.0.0 is very different than version 5.X.X, we change the structure of the SDK to support the changes on API.

Here in API reference [page](https://api-reference.checkout.com/previous/#tag/Reconciliation), you could find the examples on how to use reconciliation module with version 6.0.0.

We didn't want to introduce a lot of work to our end users, but if we did not apply this change on SDK some of the API will not match the documentation.

In some cases you need just to re import the references and that's it, there are no other major changes for reconciliation module.

Here is an example of how you can init your SDK now.
`CheckoutApi api = CheckoutSdk
    .builder()
    .previous()
    .staticKeys()
    .secretKey("secret_key")
    .environment(Environment.SANDBOX) // or Environment.PRODUCTION
    .build();`

**Comment by rotilho** [comment]
Thanks for the quick reply Armando. It still unclear why the `previous` infix was introduced, is it going to be deprecated eventually?

Checking the underlying implementation I don't see differences between the two implementation (for what I could notice). What's the motivation behind the previous `prefix` infix?

**Comment by Armando-Ibarra** [comment]
Hi @rotilho. Yes at some point you're going to be requested to migrate from our `previous` API to new one, but that will be based on your business use case.


I'd say don't worry about it for the time being, it's not going to be a change anytime soon, and this prefix change doesn't means that your API version is deprecated, Checkout decide to move into this way because they're introducing some features to new API version that are not considered on previous one.

**Comment by Armando-Ibarra** [comment]
Let us know if you have any other question.
