### ISSUE TITLE
The SDK doesn't support the Instruments API

### ISSUE THREAD

**Issue by filnko** [checkout/checkout-sdk-java#26]
Hi,

we need the Instruments API to be able to query a saved payment method:
https://api-reference.checkout.com/#tag/Instruments

Is there an ETA for integrating this?

Thanks,
Christoph

**Comment by nicolas-maalouf-cko** [comment]
Hi,

It's in progress, should be released soon:
https://github.com/checkout/checkout-sdk-java/commit/18f274720de566a3857ad99383c7eba55e269184

Kind regards

**Comment by filnko** [comment]
Hi Nicolas,

I can see that the new release contains the instruments API, but only the creation - not update or get.
The "get" would be really important for us. 

Do you know when that can be expected?

Thanks,
Christoph

**Comment by nicolas-maalouf-cko** [comment]
Hi @filnko we're working on the 2.5.0 release which will include those methods

**Comment by filnko** [comment]
Great, thanks!

**Comment by harry-peirse** [comment]
Hi @filnko, this has been released as 3.0.0 (I thought incrementing the major version number was best as we introduced a new dependency on apache http client in order to call the PATCH methods).
