### ISSUE TITLE
Fetch/get a SEPA source

### ISSUE THREAD

**Issue by cb-lakshmipriya** [checkout/checkout-sdk-java#265]
Hi Team, 

Is there any support to get or fetch the SEPA source with source_id?

**Comment by martinseco** [comment]
Hi @cb-lakshmipriya,

Could you give us some more details on what you are trying to accomplish so that we can help you? This source_id that you are referring to is from the payment?

**Comment by cb-lakshmipriya** [comment]
Hi,

Say I am using the SourcesClient to create a sepa source using createSepaSource method. Later, at some point of time, I like to fetch the created sepa source to validate some details. So, I would like to understand if there is any way to fetch the SEPA source using source Id (src_****).

**Comment by martinseco** [comment]
Hi @cb-lakshmipriya,

Thank you for clarifying! Currently that operation is not available on [Checkout's api reference](https://api-reference.checkout.com/previous/#operation/addAPaymentSource), so it is not supported in the SDKs.

**Comment by cb-lakshmipriya** [comment]
Hi, 

Thanks for clarifying. Can you please confirm one more thing? Is there any way to get the mandate details of the SEPA source using the SEPA source id (src_*****) ?

**Comment by Armando-Ibarra** [comment]
Hi @cb-lakshmipriya  there is no possible to get the mandate by SEPA using the source, this is a behavior from Checkout not from the SDK.

**Comment by Armando-Ibarra** [comment]
Closed due inactivity, let us know if you need more help.
