### ISSUE TITLE
Support Get Mandate in the previous api

### ISSUE THREAD

**Issue by rotilho** [checkout/checkout-sdk-java#281]
### Environment

* Checkout SDK version: 6.0.5
* Platform and version: Java 17
* Operating System and version: Alpine

### Description
We don't have a way to get mandate information

## Proposed Solution
Support this feature (https://api.checkout.com/sepa/mandates/src_)

- [ ] I may be able to implement this feature

**Comment by Armando-Ibarra** [comment]
Hi @rotilho 
That endpoint is available [here](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/apm/previous/sepa/SepaClient.java)

Let us know if that work for you.

**Comment by rotilho** [comment]
Totally missed. Thanks
