### ISSUE TITLE
CheckoutSettings.getProviderMode()' on a null object reference

### ISSUE THREAD

**Issue by qamarkhanInnovo** [checkout/checkout-sdk-java#284]
Hello checkout team.
we are getting this error on some devices also we provide all the necessary details while initialise the sdk.

```
binding.checkoutCardForm.set3DSListener(m3DSecureListener)
            .setEnvironment(if (BuildConfig.DEBUG) Environment.SANDBOX else Environment.LIVE)
            .setKey(if (BuildConfig.DEBUG) BuildConfig.PAYMENT_GATEWAY_ENVIRONMENT_SANDBOX else BuildConfig.PAYMENT_GATEWAY_ENVIRONMENT_LIVE)
```

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.oppwa.mobile.connect.provider.Connect$ProviderMode com.oppwa.mobile.connect.checkout.meta.CheckoutSettings.getProviderMode()' on a null object reference.
com.oppwa.mobile.connect.checkout.dialog.BaseServiceActivity$1.onServiceConnected (Unknown Source:55)

please reply us ASAP our app is already in production mode.

**Comment by Armando-Ibarra** [comment]
Can you please specify which version of SDK are you using?
Besides your `packages names` has nothing to do with Java SDK, are you sure this is the right place for this issue?

**Comment by qamarkhanInnovo** [comment]
Hello @Armando-Ibarra 
This issue report from firebase crashlytics. this is the full stracktrace which i got from there.
After this i go to the checkout sdk implementation and verify my implementation according to provided documentation, its all okay.

--> com.oppwa.mobile.connect.checkout.meta.CheckoutSettings.getProviderMode()' on a null object reference.
(then i go to checkout setting class and check what is provided mode ? you could check below i provided code).

```
public class CheckoutSettings implements Parcelable {
    @NonNull
    private String a;
    private String b;
    @NonNull
    private ProviderMode c;
```
this is provider mode enum class

```
public static enum ProviderMode {
        LIVE,
        TEST;

        private ProviderMode() {
        }
    }
```
if you check my above comment where i send mode like .setEnvironment(if (BuildConfig.DEBUG) Environment.SANDBOX else Environment.LIVE) live or sandbox.
i dont know why this issue comes on some devices and other are okay.
i used this sdk `implementation 'com.github.checkout:frames-android:3.0.1'`

![Screenshot_2022-10-31-11-48-02-74_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/90673233/199168354-6feca97f-31f4-47d8-a3f6-1c60b8eda14c.jpg)

**Comment by Armando-Ibarra** [comment]
Hi @qamarkhanInnovo 
I see you already opened this issue on frames [repository](https://github.com/checkout/frames-android/issues/141)

Your issue is regarding to frames-android SDK, is there anything that you need from **Java SDK**, this repository belongs to a Java runtime application related to a back end implementation, mobile implementations belongs to another team, so not pretty sure how can we help you right now.

**Comment by Armando-Ibarra** [comment]
Please refer to https://github.com/checkout/frames-android
to follow up this issue.
