### ISSUE TITLE
Support for AFT in Previous API PaymentRequest

### ISSUE THREAD

**Issue by pete-me** [checkout/checkout-sdk-java#304]
### Environment

* Checkout SDK version: 6.0.10
* Platform and version:  Any (Checkout Previous API)
* Operating System and version: Any

### Description

Based on the official [Previous Documentation for AFT](https://www.checkout.com/docs/previous/payments/manage-payments/account-funding-transactions), the field **processing.senderInformation** is required for VISA transactions. However, [PaymentRequest   for previous API](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/previous/request/PaymentRequest.java) has no such field, thus Checkout SDK for Java (as of version 6.0.10) can not be used to perform AFT. 

The attribute already exists as simply **sender** on the [new API PaymentRequest](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/request/PaymentRequest.java).

## Proposed Solution

Please add processing.senderInformation attribute to Previous API PaymentRequest.

**Comment by stephen-gilbert-cko** [comment]
[senderInformation](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/previous/request/SenderInformation.java) should still be available under [ProcessingSettings](https://github.com/checkout/checkout-sdk-java/blob/b4a0e132b4764703e6a13bd47e0025081f6c95a1/src/main/java/com/checkout/payments/ProcessingSettings.java#L109).

Are you able to build the request like so (replace card source with relevant source):
```
CheckoutApi api = CheckoutSdk
    .builder()
    .previous()
    .staticKeys()
    .secretKey("secret_key")
    .environment(Environment.SANDBOX)
    .build();

RequestCardSource source = RequestCardSource.builder()
    .name("name")
    .number("4242424242424242")
    .expiryMonth(12)
    .expiryYear(2025)
    .cvv("100")
    .stored(true)
    .build();

PaymentRequest paymentRequest = PaymentRequest.builder()
    .source(source)
    .capture(true)
    .reference("reference")
    .amount(10)
    .currency(Currency.GBP)
    .processing(ProcessingSettings.builder()
        .aft(true)
        .senderInformation(SenderInformation.builder()
            .address("90 Tottenham Court Road")
            .city("London")
            .country(CountryCode.GB)
            .firstName("John")
            .LastName("Smith")
            .build())
        .build())
    .build();
```

**Comment by pete-me** [comment]
Hi @stephen-gilbert-cko , although I see it in the source code now, the 6.0.10 release does not contain SenderInformation yet. 

Perhaps a new release needs to be made for the changes to take effect.

**Comment by stephen-gilbert-cko** [comment]
Thanks for raising. I'm just checking this with the team now and will let you know once resolved.

**Comment by Armando-Ibarra** [comment]
Hi @pete-me 

Yes, we are aware about that `senderInformation` field, we already filled a PR #303  so we just need to merge and release it, this should be done on Monday

Thanks @stephen-gilbert-cko for covering the AFT question.

**Comment by kahramani-tw** [comment]
Hi @Armando-Ibarra, looks like there is a release attempt that is failed yesterday.
https://github.com/checkout/checkout-sdk-java/commit/c59f0be84566135dcf1111b8d244d5d997635409

Any plans to make another release soon. Currently we are also blocked migrating to the latest java sdk.
