### ISSUE TITLE
Getter For Gson Configuration in GsonSerializer

### ISSUE THREAD

**Issue by dlabey** [checkout/checkout-sdk-java#307]
### Description
We are building a Checkout.com simulator for internal load testing with Spring Boot and are setting the  JSON mapper to use GSON instead of the default Jackson implementation. We are using the Checkout.com SDK for our objects. Instead of having to copy and paste the GSON configuration stored in [GsonSerializer](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/GsonSerializer.java#L62) it would be ideal if GsonSerializer could be a public class with a getter for the Gson object and/or the GsonBuilder object so it could be extended.

## Proposed Solution
- Make GsonSerializer a public class
- Add a public getter for Gson
- Add a public getter for GsonBuilder

- [x] I may be able to implement this feature

**Comment by Armando-Ibarra** [comment]
Sorry for the delay on this, released #313 let us know if you face any problem
