### ISSUE TITLE
Field is undocumented

### ISSUE THREAD

**Issue by nkavian** [checkout/checkout-sdk-java#31]
Please add the possible values for the `scheme` field within source: https://api-reference.checkout.com/#operation/getPaymentDetails

For now I'm assuming it's the `Card type` found here: https://docs.checkout.com/testing/test-card-numbers

**Comment by nicolas-maalouf-cko** [comment]
Hi @nkavian here are the possible values:

* American Express
* Visa
* Mastercard
* Diners Club International
* JCB
* Discover

Kind regards

**Comment by nkavian** [comment]
The correct values that I've seen seem to be:

- `Amex`
- `DinersClub`
- `Discover`
- `JCB`
- `Mastercard`
- `Visa`

Irrespective of which strings are correct, would you be willing to please update the API documentation so that other people can benefit by having it properly documented?

**Comment by nicolas-maalouf-cko** [comment]
Hi @nkavian are you sure you saw these in payment responses and not in webhook payloads?

Payment response -> American Express
Webhook -> AMEX

Payment response -> Visa
Webhook -> VISA

Payment response -> Mastercard
Webhook -> MASTERCARD

Payment response -> Diners Club International
Webhook -> DINERSCLUB

Payment response -> JCB
Webhook -> JCB

Payment response -> Discover
Webhook -> DISCOVER

**Comment by nkavian** [comment]
Ah, sorry for the confusion. I was mistaken about the values I was using. I just performed a payment with each card type using the JavaScript library and the `Frames.submitCard` gave these values for `data.scheme`:

- AMERICAN EXPRESS
- Diners Club International
- Discover
- JCB
- Mastercard
- Visa

Same values as you originally shared, except Amex seems to be all caps.
