### ISSUE TITLE
webhook signature verification problem

### ISSUE THREAD

**Issue by 846763951** [checkout/checkout-sdk-java#325]
When receiving webhook notification, we use EventResponse to receive it, but there is a problem that we want to hash it to generate HMAC. At this time, should we hash it with EventResponse.getData() and the provided key to generate HMAC or directly use EventResponse Hashing it with the supplied key to generate the HMAC?

**Comment by 846763951** [comment]
@RequestMapping("/notify")
    public R notify(@RequestBody EventResponse eventResponse, @RequestHeader(value = "Cko-Signature", required = false) String ckoSignature) {
        log.info("CheckoutNotify:{}", eventResponse);
         //Signature verification
}

**Comment by armando-ibarra-cko** [comment]
Hi @846763951
Why do you want to do this inside the SDK? Can't you just grab the response object and hash?
This is some custom behaviour, what we can do and is one of the top things on my list right now, is to make all the request, responses not final, so that everyone could implement his own behaviour as needed

**Comment by 846763951** [comment]
Ok, got it! Another question is, what happens when we configure two different webhook addresses? Will both addresses receive callbacks or only one?

**Comment by 846763951** [comment]
Hello@armando-ibarra-cko ，
I want to know what parameters are included in webhook to generate cco-signature. I have tried many methods, but still failed to check the Signature!

Data returned by webhook

{id=evt_gjqawvqtieru7hc76ckm4vubf4, type=payment_declined, version=1.0.26, created_on=2023-03-29T08:19:27.8915504Z, data={id=pay_524fom3izege7j2akasx5xcntu, action_id=act_leyq5f445o5ufpronl4s6agyra, reference=8168007795860000, amount=1000, auth_code=, currency=CNY, payment_type=Regular, processed_on=2023-03-29T08:19:27.6631717Z, processing={acquirer_transaction_id=11354820230329081926MRG4RHRD90329, retrieval_reference_number=308808113548}, response_code=20182, response_summary=Policy, risk={flagged=false, score=0}, scheme_id=MRG4RHRD90329, source={id=src_ig6qc5ygtalujn6fpefzs3l6zm, type=card, billing_address={}, expiry_month=10, expiry_year=2025, scheme=MASTERCARD, last_4=6949, fingerprint=2D7B054FDDAE8ACA33723F59B5CA47910E9188FD571F8E1BF838C0907B80A3A3, bin=559786, card_type=PREPAID, card_category=CONSUMER, issuer=HKT PAYMENT LIMITED, issuer_country=HK, product_id=MRG, product_type=MasterCard® Prepaid Card (Non-U.S.), avs_check=U, cvv_check=U}, event_links={payment=https://api.checkout.com/payments/pay_524fom3izege7j2akasx5xcntu, payment_actions=https://api.checkout.com/payments/pay_524fom3izege7j2akasx5xcntu/actions}}, _links={self={href=https://api.checkout.com/workflows/events/evt_gjqawvqtieru7hc76ckm4vubf4}, subject={href=https://api.checkout.com/workflows/events/subject/pay_524fom3izege7j2akasx5xcntu}, payment={href=https://api.checkout.com/payments/pay_524fom3izege7j2akasx5xcntu}, payment_actions={href=https://api.checkout.com/payments/pay_524fom3izege7j2akasx5xcntu/actions}}}

**Comment by armando-rodriguez-cko** [comment]
Hi @846763951,

You can read in the documentation:
"...Using signatures is simple. All you need to do is take the webhook's body and apply the SHA-256 hash function to it, using your key as the hash key. You then compare the resulting HMAC to the one contained in the Cko-Signature header. If the HMACs are identical, then the data corresponds to what we sent. If they are different, this indicates that the data has been intercepted and altered in some way..."

https://www.checkout.com/docs/workflows/set-up-your-webhook-receiver#Webhook_signatures .

I hope it has helped you.
