### ISSUE TITLE
https://www.checkout.com/docs/previous/integrate/hosted-payments-page#Who_is_Hosted_Payments_Page_for

### ISSUE THREAD

**Issue by Rahim7588** [checkout/checkout-sdk-java#343]
### Environment

* Checkout SDK version:
* Platform and version:
* Operating System and version:

## Proposed Solution

- [x] I may be able to implement this feature

**Comment by armando-rodriguez-cko** [comment]
Hello @Rahim7588 can you explain more your issue?
Thank you.

**Comment by armando-rodriguez-cko** [comment]
@Rahim7588 we close this issue due missing information.
