### ISSUE TITLE
Previous - List payments from a payout

### ISSUE THREAD

**Issue by rotilho** [checkout/checkout-sdk-java#348]
### Environment

* Checkout SDK version: 6.0.19
* Platform and version: JDK 17
* Operating System and version: Alpine 3.8

## Proposed Solution

Currently, the statement API allows listing payouts, but there's no way to query the payments for a specific payout through this SDK. 

Workaround: Use the REST interface directly

- [ ] I may be able to implement this feature

**Comment by armando-rodriguez-cko** [comment]
Thank you @rotilho, we will take a look.

**Comment by stephen-gilbert-cko** [comment]
@armando-rodriguez-cko I believe we'd need to add support for the `/reporting/statements/{id}/payments` endpoint + query params `payout_id` and `payout_currency` listed [here](https://www.checkout.com/docs/previous/reporting-and-insights/reconciliation-api/statements-endpoint#2._Statement_ID_/_Payments)

**Comment by armando-rodriguez-cko** [comment]
Thank you @stephen-gilbert-cko
