### ISSUE TITLE
Wrong value mapping

### ISSUE THREAD

**Issue by shiuh-yaw** [checkout/checkout-sdk-java#349]
The returned value state in API documentation was fast_funds instead of fast_founds

https://github.com/checkout/checkout-sdk-java/blob/8f786cec6791e67e705124ff0213a5aad595a91e/src/main/java/com/checkout/metadata/card/PayoutsTransactionsType.java#L11C35-L11C35

**Comment by armando-rodriguez-cko** [comment]
Thank you @shiuh-yaw! We will fix it.
