### ISSUE TITLE
Production secret keys don't match the regex

### ISSUE THREAD

**Issue by nuno-bras** [checkout/checkout-sdk-java#351]
### Environment

* Checkout SDK version: 6.0.19
* Platform and version:
* Operating System and version: Darwin Kernel Version 22.4.0

### Description

Using the existing 2 years old production secret keys, the regex defined at `com.checkout.StaticKeysSdkCredentials.SECRET_KEY_PATTERN` doesn't validate my keys.

### Expected behavior

It should accept these old keys, since they are still valid when executing curl commands or with manual java rest client implementations.

### Current behavior

The library throws a `CheckoutArgumentException("invalid secret key");`

### Steps to reproduce

Create a CheckoutApi using the builder `new CheckoutSdkBuilder().staticKeys().secretKey("my-private-key").environment(Environment.PRODUCTION).build();`

### Possible solution

Improve the regex to support these keys. Since I don't know their pattern (only my own), I cannot ensure the solution is valid for all keys.

- [ ] I may be able to implement this bug fix

**Comment by armando-rodriguez-cko** [comment]
Hi @nuno-bras! Thank you, we will check and we will give you a solution.

**Comment by armando-rodriguez-cko** [comment]
Hi @nuno-bras! Please can you renew you key? Do you have a legacy key?

**Comment by armando-rodriguez-cko** [comment]
Hi @nuno-bras, what pattern does it follow you key?

`^sk_(test_)?(\\w{8})-(\\w{4})-(\\w{4})-(\\w{4})-(\\w{12})$`
or
`^sk_(sbox_)?[a-z2-7]{26}[a-z2-7*#$=]$`

Now, we are using the last:

`^sk_(sbox_)?[a-z2-7]{26}[a-z2-7*#$=]$`

Thank you

**Comment by nuno-bras** [comment]
> Hi @nuno-bras! Please can you renew you key? Do you have a legacy key?

Hello,
I assume it's a legacy key from the initial integration. It's at least 2 years old.
To renew the key, as a developer, I cannot confirm if my customers, who also use this key for their own environments and products, will switch to another key, since this one has been working, and it still is.

I think having this regex backwards compatible with older keys makes it easier to be adopted by developers because it doesn't require their customers to switch keys.

**Comment by nuno-bras** [comment]
> Hi @nuno-bras, what pattern does it follow you key?
> 
> `^sk_(test_)?(\\w{8})-(\\w{4})-(\\w{4})-(\\w{4})-(\\w{12})$` or `^sk_(sbox_)?[a-z2-7]{26}[a-z2-7*#$=]$`
> 
> Now, we are using the last:
> 
> `^sk_(sbox_)?[a-z2-7]{26}[a-z2-7*#$=]$`
> 
> Thank you

For me, it's the first regex.
I did a quick test, and that pattern matches my key.

Thanks for the quick feedback.

**Comment by armando-rodriguez-cko** [comment]
Hi @nuno-bras in this case you only can use previous version or legacy:

API reference:
https://api-reference.checkout.com/previous/

SDK:
https://github.com/checkout/checkout-sdk-java/blob/5647f224db93a491915fc3df23ad85f72adfda5b/src/main/java/com/checkout/PreviousStaticKeysSdkCredentials.java#L5

If you want to upgrade you can check this documentation:
https://www.checkout.com/docs/previous/upgrade-to-our-new-platform

The migration must be done carefully.

**Comment by armando-rodriguez-cko** [comment]
Hi @nuno-bras, if you don't have more questions, we will close the issue. Thank you.
