### ISSUE TITLE
GetPaymentResponse source type is incomplete

### ISSUE THREAD

**Issue by nuno-bras** [checkout/checkout-sdk-java#352]
### Environment

* Checkout SDK version: 6.0.19
* Platform and version:
* Operating System and version: Darwin Kernel Version 22.4.0

### Description

The payment details endpoint returns the card data, used in the payment, attached to the source field. At this version, the class returns a ResponseSource interface. For the developer, isn't clear that there are other classes who implement this interface, and using a cast to the correct class provides all fields returned by the API.

## Proposed Solution

Instead of returning a ResponseSource in the GetPaymentResponse, return a CardResponseSource.

- [ ] I may be able to implement this feature

**Comment by armando-rodriguez-cko** [comment]
Hi @nuno-bras! Thank you for your comments, we will try to implement better.

**Comment by armando-rodriguez-cko** [comment]
Hi @nuno-bras!
You can find the class here:
https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/response/source/CardResponseSource.java

And in the GsonSerializer class you can see the adapters: 
https://github.com/checkout/checkout-sdk-java/blob/5647f224db93a491915fc3df23ad85f72adfda5b/src/main/java/com/checkout/GsonSerializer.java#L89
https://github.com/checkout/checkout-sdk-java/blob/5647f224db93a491915fc3df23ad85f72adfda5b/src/main/java/com/checkout/GsonSerializer.java#L95

**Comment by armando-rodriguez-cko** [comment]
We close this issue due a inactivity.
