### ISSUE TITLE
Add financial action reports API integration

### ISSUE THREAD

**Issue by nuno-bras** [checkout/checkout-sdk-java#353]
### Environment

* Checkout SDK version: 6.0.19
* Platform and version:
* Operating System and version: Darwin Kernel Version 22.4.0

### Description

The API has an endpoint to list of actions applied to the payment. This SDK doesn't have that endpoint implemented. The only workaround is to manually implement using another RestClient library.

## Proposed Solution

Add another client to the reports API to support this endpoint: https://api-reference.checkout.com/#operation/getFinancialActions

- [ ] I may be able to implement this feature

**Comment by armando-rodriguez-cko** [comment]
Hello @nuno-bras! Do you mean this endpoint: https://github.com/checkout/checkout-sdk-java/blob/5647f224db93a491915fc3df23ad85f72adfda5b/src/main/java/com/checkout/financial/FinancialClientImpl.java#L20?

**Comment by nuno-bras** [comment]
Dear @armando-rodriguez-cko 
That's exactly what I was looking for. I searched inside the reports, which I thought it was the correct place, looking how the documentation aggregates that API inside the report's category.

I think this issue can be closed. As a suggestion: change the JAVA example in Checkout docs to use the SDK.

**Comment by armando-rodriguez-cko** [comment]
Thank you @nuno-bras! We are glad.
Please can you share with us if you have a proposal for the use of the SDK? What do you mean? Where can we find the example that for you is not correct?
Thank you again.

**Comment by nuno-bras** [comment]
@armando-rodriguez-cko 

Gladly! I've attached a screenshot with the location of the JAVA code which could use the SDK as an example.
![image](https://github.com/checkout/checkout-sdk-java/assets/144787299/84a093fe-bb26-4c06-a059-332eb1072c0c)

**Comment by armando-rodriguez-cko** [comment]
Thank you @nuno-bras! The sample in this case should be:
```java

// For more information please refer to https://github.com/checkout/checkout-sdk-java
import com.checkout.CheckoutApi;
import com.checkout.CheckoutApiException;
import com.checkout.CheckoutArgumentException;
import com.checkout.CheckoutAuthorizationException;
import com.checkout.CheckoutSdk;
import com.checkout.Environment;
import com.checkout.OAuthScope;
import com.checkout.financial.FinancialActionsQueryFilter;
import com.checkout.financial.FinancialActionsQueryResponse;

// API Keys
CheckoutApi api = CheckoutSdk.builder()
    .staticKeys()
    .secretKey("secret_key")
    .environment(Environment.SANDBOX) // or Environment.PRODUCTION
    .build();

// OAuth
CheckoutApi api = CheckoutSdk.builder()
    .oAuth()
    .clientCredentials("client_id", "client_secret")
    .scopes(OAuthScope.FINANCIAL_ACTIONS, OAuthScope.FINANCIAL_ACTIONS_VIEW) // more scopes available
    .environment(Environment.SANDBOX) // or Environment.PRODUCTION
    .build();

FinancialActionsQueryFilter query = FinancialActionsQueryFilter.builder()
    .paymentId("payment_id")
    .limit(5)
    .build();

try {
    FinancialActionsQueryResponse response = api.financialClient().query(query).get();
} catch (CheckoutApiException e) {
    // API error
    String requestId = e.getRequestId();
    int statusCode = e.getHttpStatusCode();
    Map<String, Object> errorDetails = e.getErrorDetails();
} catch (CheckoutArgumentException e) {
    // Bad arguments
} catch (CheckoutAuthorizationException e) {
    // Invalid authorization
}
```

We are updating the samples.

**Comment by armando-rodriguez-cko** [comment]
We close the issue, thanks!
