### ISSUE TITLE
Need to understand the impact of new api key generation

### ISSUE THREAD

**Issue by sonilumi** [checkout/checkout-sdk-java#358]
### Environment

* Checkout SDK version: Currently we are on 2.0.10 and trying to move to 6.0.20
* Platform and version: Java sdk 
* Operating System and version:

### Description
Need to understand the impact of new api key generation
- For our system if we move to version upgrade we need to re generate our api keys as well - (Let me know if this understanding is correct)
- Now if we re generate the new api key what will happen to the old payment refund request will that be processed on this new api key?
- Is there a way to do gradual change instead of big boom deployment while doing the version upgrade.

### Expected behavior
- we expect system to process the old api generated refund requests as well for backward compatibility.

**Comment by armando-rodriguez-cko** [comment]
Thank you @sonilumi for your question.

You can check the documentation:
https://www.checkout.com/docs/previous/upgrade-to-our-new-platform
https://www.checkout.com/docs/previous/upgrade-to-our-new-platform/get-started

### First:
> For our system if we move to version upgrade we need to re generate our api keys as well - (Let me know if this understanding is correct)

**Yes**

### Second
> Now if we re generate the new api key what will happen to the old payment refund request will that be processed on this new api key?

![Screenshot 2023-09-22 at 12 32 09](https://github.com/checkout/checkout-sdk-java/assets/127134616/1df198c4-6ed2-48cf-bf1b-996b11ff995f)

**No**

### Third
> Is there a way to do gradual change instead of big boom deployment while doing the version upgrade.

https://www.checkout.com/docs/previous/upgrade-to-our-new-platform/go-live

Please contact with the Support team at [platformupgrade@checkout.com](mailto:platformupgrade@checkout.com?Subject=Migration%20Query) for this question.

**Comment by armando-rodriguez-cko** [comment]
Hi @sonilumi, if you don't have more questions, we will close the issue. Thank you.
