### ISSUE TITLE
Add ability to configure default response status code for ApacheHttpClientTransaport in performCall

### ISSUE THREAD

**Issue by dlabey** [checkout/checkout-sdk-java#372]
### Environment

* Checkout SDK version: 6.0.26
* Platform and version: Java 8
* Operating System and version: Amazon Linux 2

### Description
In the ApacheHttpClientTransport class of the Checkout SDK, in the [performCall method](https://github.com/checkout/checkout-sdk-java/blob/6.0.26/src/main/java/com/checkout/ApacheHttpClientTransport.java#L178), the default catch-all status code for the response is a bad request (400); this is thrown for a SocketTimeoutException for example. We want this status code to be customizable with the ability to provide an alternate status code, such as an internal server error (500) or gateway timeout (504).

## Proposed Solution
Could you provide a way to customize this with the configuration object, with the default being the existing bad request and the ability to pass a custom status code?

- [x] I may be able to implement this feature

**Comment by armando-rodriguez-cko** [comment]
Thank you @dlabey. We appreciate your contribution.
