### ISSUE TITLE
Testing Pull Requests

### ISSUE THREAD

**Issue by harry-peirse** [checkout/checkout-sdk-java#4]
Currently the test suite requires credentials to run against the Checkout.com sandbox. These have particular access in order to call all endpoints and so should be protected. They are therefore stored in secure environment variables in TravisCI.
This means that pull request builds will always fail, as to protect the variables TravisCI does not allow them to be used by pull request builds.
We need to consider the options and make a decision how to proceed... do we find another way of testing pull requests, or always merge to dev in order to run the tests?

**Comment by nicolas-maalouf-cko** [comment]
Hi @harry-peirse 
Do we have any other options to make them work with PRs?

If not we'll need to always merge to dev to test I guess

**Comment by harry-peirse** [comment]
We could make the credentials available, but that is less desirable. I'm inclined to say merging to dev is the only approach to get full tests run. But we could change the build script to do just a compile and unit tests (unconnected to sandbox) on pull requests to provide better feedback to contributors and more initial reassurance of pull request quality.

**Comment by harry-peirse** [comment]
I'd like to sleep on it and see what ideas I can come up with ;)

**Comment by louis-tw** [comment]
There's a way to add and use secrets in a github repo, I never used it, but worth checking if it could work

**Comment by harry-peirse** [comment]
Yes you're right, however they aren't made available to pull requests, as it would allow anyone to scrape them - by sending the variables elsewhere with some modified build script for instance.
I'm still sleeping on it! 😴 Ideas welcome...

**Comment by harry-peirse** [comment]
I've added a very basic Wiremock based test would could become the start of this. We could divide the tests into three categories... standard unit tests, wiremock based scenario tests, and sandbox based integration tests. The first two could be run by anyone without valid credentials and could be quite quick to execute. Will need to figure out how to make it straightforward to exclude the integration tests from regular gradle builds though.

**Comment by rsaestrela** [comment]
Hi everyone! Testing in pull requests will be added in the upcoming weeks with the transition from TravisCI to GitHub Actions. Secrets will be stored in GitHub, and the new workflow may as well include static analysis. Unless this becomes an issue in future, unit and integration tests will always run on PRs and on dev/master branches (when the code gets merged).
