### ISSUE TITLE
Missing enum value authorised_signatory in EntityRoles

### ISSUE THREAD

**Issue by sansnom** [checkout/checkout-sdk-java#405]
### Environment
* Checkout SDK version: 6.1.2 (latest)

### Description
Missing enum value authorised_signatory in [EntityRoles](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/accounts/EntityRoles.java).

### Steps to reproduce
Create a sub entity. Use the AccountsClient#getEntity and see that Representative#getRoles return null when the representative is an authorized signatory.

### Possible solution
https://github.com/checkout/checkout-sdk-java/pull/404

Thanks.

**Comment by armando-rodriguez-cko** [comment]
Thank you @sansnom!
