### ISSUE TITLE
Supporting merchant_category_code under Processing 

### ISSUE THREAD

**Issue by mohamad-rmeity-cko** [checkout/checkout-sdk-java#411]
### Environment
* Checkout SDK version: 6.2.1
* Platform and version: Java SDK
* Operating System and version: N/A

### Description
Hello Team, Remitly (T1) have started processing transactions under 2 MCCs, and would like to have the ability to consume the MCC as part of the response. I'm aware that it is currently not listed in the API reference, and this is something that I have raised with our docs team to get it resolved. It is however listed under the 'GET Payment Details', and has the same type: 
https://api-reference.checkout.com/#operation/getPaymentDetails!c=200&path=0/processing/merchant_category_code&t=response

## Proposed Solution
Adding merchant_category_code under https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/PaymentProcessing.java

**Comment by armando-rodriguez-cko** [comment]
Hi @mohamad-rmeity-cko I believe that you are looking for this class: https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/response/ProcessingData.java

**Comment by armando-rodriguez-cko** [comment]
New release launched with the changes: https://github.com/checkout/checkout-sdk-java/pull/415
