### ISSUE TITLE
Instrument Api missing Customer and Account Holder

### ISSUE THREAD

**Issue by philipgrivell-bjss** [checkout/checkout-sdk-java#43]
The com.checkout.instruments.CreateInstrumentRequest class is missing both Customer and AccountHolder elements, and looking at CustomerRequest within the instrument package it's missing name, email and phone. Can these classes be updated?

**Comment by philipgrivell-bjss** [comment]
Similarly com.checkout.instruments.CreateInstrumentResponse is also missing customer details.

**Comment by nevvermind** [comment]
I'm going to hijack this issue to also report that the `fingerprint` field is also not mapped in the `CreateInstrumentResponse` class.

**Comment by rsaestrela** [comment]
Hi @philipgrivell-bjss. Thank you for reporting this issue. Indeed, these classes are missing the attributes you mentioned. This was already detected and we will come up with a fix in the upcoming weeks.

**Comment by Armando-Ibarra** [comment]
Hello @philipgrivell-bjss 

In the latest release ([see](https://github.com/checkout/checkout-sdk-java/releases/tag/4.3.1))
We added the missing fields for the Customer Client, please let us know any thought.

Regards.
