### ISSUE TITLE
Unability to cancel request or handle connection timeout

### ISSUE THREAD

**Issue by gaskoin** [checkout/checkout-sdk-java#5]
Underlying transport implementation uses plain `HttpURLConnection`. This object has configurable connection and read timeouts:

```java
connection.setConnectTimeout(connectionTimeout);
connection.setReadTimeout(readTimeout);
```

But this is not configurable via API so in fact we always use default connection/read timeout (unlimited). We can use `CompletableFuture.get(long, TimeUnit)` for getting the result with timeout but since this task cannot be cancelled in any way the request can complete fine.

We can fall into situation that we will timeout our request and tell customer back that it failed but then we will get *payment_captured* event. How to handle such situations? This makes this API rather not usable

**Comment by harry-peirse** [comment]
Hi, thanks for raising this. You make a really good point. I'll take a look.

**Comment by gaskoin** [comment]
Do you have some workarounds or suggestions for now?

**Comment by harry-peirse** [comment]
You can provide your own implementation of the Transport interface. Have a
look at the Spring sample for an example of wiring something like this
together.

**Comment by gaskoin** [comment]
Thanks for fix. Separating Read from Connect timeout would be nice though!
