### ISSUE TITLE
PlatformType.CLASSIC pattern error

### ISSUE THREAD

**Issue by imyxiao** [checkout/checkout-sdk-java#71]
`CLASSIC("^sk_([a-z]+)_(\\w{8})-(\\w{4})-(\\w{4})-(\\w{4})-(\\w{12})$", "^pk_([a-z]+)_(\\w{8})-(\\w{4})-(\\w{4})-(\\w{4})-(\\w{12})$"),`

production  secretKey and publicKey validate error

**Comment by rsaestrela** [comment]
Hi @imyxiao. Thank you for reporting this issue. Version 4.0.0 contains a big changeset to support different customer keys and it looks that a bug was introduced. We'll release a new version tomorrow fixing this issue.

For the moment, please use the SDK version `3.7.0`. Marking this as a bug, will provide you a confirmation when a new library is released.

**Comment by rsaestrela** [comment]
Version 4.1.1 was released containing a fix for this issue. Thanks!

**Comment by imyxiao** [comment]
ok, thank you .
